project_name: disco

release:
   name_template: "Version {{.Version}}"

   github:
    owner: minio
    name: disco

before:
  hooks:
    - go mod tidy

builds:
  -
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

archives:
  - format: binary

changelog:
  sort: asc

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    extra_files:
      - ca-certificates.crt
    image_templates:
      - minio/disco:{{ .Tag }}
      - minio/disco:latest
