apiVersion: v1
kind: Service
metadata:
  name: minio-disco
  labels:
    name: minio-disco
spec:
  ports:
    - port: 53
      protocol: UDP
      name: dns
    - port: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: minio-disco
