apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-disco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-disco
  template:
    metadata:
      labels:
        app: minio-disco
    spec:
      serviceAccountName: minio-disco-sa
      containers:
        - name: minio-disco
          image: dvaldivia/disco:latest
          imagePullPolicy: "Always"
          args:
            - /disco
            - server
          ports:
            - containerPort: 53
              protocol: UDP
              name: dns
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
