kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minio-disco-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-disco-sa-role
subjects:
  - kind: ServiceAccount
    name: minio-disco-sa
    namespace: default
