apiVersion: v1
kind: Service
metadata:
  name: disco
  labels:
    name: disco
spec:
  ports:
    - port: 53
      protocol: UDP
      name: dns
    - port: 53
      protocol: TCP
      name: dns-tcp
    - port: 8080
      name: http
  selector:
    app: disco
